version: '3.4'
services:
  rasa:
    image: rasa-bot:latest
    build: "./"
    restart: always
    working_dir: "/app"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./actions:/app/actions
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\""
    ports:
      - '5005:5005'
    public: true
    networks:
      - all

  rasa-actions:
    build: "./"
    image: rasa-bot:latest
    restart: always
    working_dir: "/app"
    volumes:
      - ./actions:/app/actions
    command: ["rasa","run","actions"]
    ports:
    - '5055:5055'
    public: true
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"